// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.4.2 (260430a), https://www.lohrfink.de/lfet
// From decision table
// "/home/constantin/Development/github/uniqueck/asciidoctor-jira/lfet/common/jiraConfig.lfet"
// 12.05.2026 16:30
//
// Changes to this code resulting from refactorings can be synchronised
// with LF-ET using the function "Scrapbook Import".
//
// Prolog Decision Table ---->
function jiraConfig (parent, attrs) {
  const doc = parent.getDocument()
  const _jiraConfig = {
    toJSON: function () {
      const result = {}
      for (const x in this) {
        if (x !== 'auth') {
          result[x] = this[x]
        } else {
          if (x === 'auth' && typeof this[x] === 'object') {
            result[x] = JSON.stringify(this[x]).replace(/./g, '*')
          } else if (x === 'clientId' || x === 'clientSecret') {
            result[x] = this[x].replace(/./g, '*')
          }
        }
      }
      return result
    }
  }
  // Prolog Decision Table <----
  // Condition C01: client id defined
  if (process.env.JIRA_CLIENT_ID) {
    // Condition C02: client secret defined
    if (process.env.JIRA_CLIENT_SECRET) {
      // Condition C04: cloud name defined
      if (process.env.JIRA_CLOUD_NAME) {
        // Rule R01 ---->
        // Trace ---->
        doc.getLogger().debug(`jiraConfig - 20260512.163013 - 1 / 6 - ${JSON.stringify(_jiraConfig)}`)
        // Trace <----
        // Action A01/01: create OAuth 2.0 access token / true / OAuth 2.0 access token should be created
        _jiraConfig.authUrl = 'https://auth.atlassian.com/oauth/token'
        _jiraConfig.createOAuthToken = true
        // Action A02/01: set rest api base url / X / https://api.atlassian.com/ex/jira/
        _jiraConfig.restApiBaseUrl = 'https://api.atlassian.com/ex/jira/'
        // Action A03/01: set auth mode / OAuth2.0 / https://support.atlassian.com/user-management/docs/create-oauth-2-0-credential-for-service-accounts/
        _jiraConfig.clientId = process.env.JIRA_CLIENT_ID
        _jiraConfig.clientSecret = process.env.JIRA_CLIENT_SECRET
        // Action A04: set cloud name
        _jiraConfig.cloudIdName = process.env.JIRA_CLOUD_NAME
        // Rule R01 <----
      } else {
        // Rule R02 ---->
        // Trace ---->
        doc.getLogger().debug(`jiraConfig - 20260512.163013 - 2 / 6 - ${JSON.stringify(_jiraConfig)}`)
        // Trace <----
        // Action A05/02: log mandatory information is missing / CN / Cloud name is missing
        throw new Error('Cloud name is missing')
        // Rule R02 <----
      }
    } else {
      // Rule R03 ---->
      // Trace ---->
      doc.getLogger().debug(`jiraConfig - 20260512.163013 - 3 / 6 - ${JSON.stringify(_jiraConfig)}`)
      // Trace <----
      // Action A05/01: log mandatory information is missing / AUTH / OAuth 2.0 client id/secret or API token is missing
      throw new Error('OAuth 2.0 client id/secret or API token is missing')
      // Rule R03 <----
    }
  } else {
    // Condition C03: apitoken defined
    if (process.env.JIRA_API_TOKEN) {
      // Condition C04: cloud name defined
      if (process.env.JIRA_CLOUD_NAME) {
        // Rule R04 ---->
        // Trace ---->
        doc.getLogger().debug(`jiraConfig - 20260512.163013 - 4 / 6 - ${JSON.stringify(_jiraConfig)}`)
        // Trace <----
        // Action A01/02: create OAuth 2.0 access token / false / OAuth 2.0 access token should not be created
        _jiraConfig.createOAuthToken = false
        // Action A02/01: set rest api base url / X / https://api.atlassian.com/ex/jira/
        _jiraConfig.restApiBaseUrl = 'https://api.atlassian.com/ex/jira/'
        // Action A03/02: set auth mode / API token / https://support.atlassian.com/user-management/docs/manage-api-tokens-for-service-accounts/
        _jiraConfig.auth = { Authorization: `Bearer ${process.env.JIRA_API_TOKEN}` }
        // Action A04: set cloud name
        _jiraConfig.cloudIdName = process.env.JIRA_CLOUD_NAME
        // Rule R04 <----
      } else {
        // Rule R05 ---->
        // Trace ---->
        doc.getLogger().debug(`jiraConfig - 20260512.163013 - 5 / 6 - ${JSON.stringify(_jiraConfig)}`)
        // Trace <----
        // Action A05/02: log mandatory information is missing / CN / Cloud name is missing
        throw new Error('Cloud name is missing')
        // Rule R05 <----
      }
    } else {
      // Rule R06 ---->
      // Trace ---->
      doc.getLogger().debug(`jiraConfig - 20260512.163013 - 6 / 6 - ${JSON.stringify(_jiraConfig)}`)
      // Trace <----
      // Action A05/01: log mandatory information is missing / AUTH / OAuth 2.0 client id/secret or API token is missing
      throw new Error('OAuth 2.0 client id/secret or API token is missing')
      // Rule R06 <----
    }
  }
  // Epilog Decision Table ---->
  return _jiraConfig
}

module.exports = {
  createConfig: (parent, attrs) => {
    return jiraConfig(parent, attrs)
  }
}
// Epilog Decision Table <----

// End of generated JavaScript source code
// Generated by LF-ET 2.4.2 (260430a), https://www.lohrfink.de/lfet
