= Asciidoctor Jira Extension
Constantin Krüger <https://github.com/uniqueck[@uniqueck]>
:compat-mode!:
:page-layout: base
:toc: macro
:toclevels: 2
ifndef::env-github[:icons: font]
ifdef::env-github[]
:badges:
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:table-caption!:
:warning-caption: :warning:
endif::[]

ifdef::badges[]
image:https://github.com/uniqueck/asciidoctor-jira/actions/workflows/build-js.yml/badge.svg?branch=main[link=https://github.com/uniqueck/asciidoctor-jira/actions/workflows/build-js.yml]
image:http://img.shields.io/npm/v/asciidoctor-jira.svg[link=https://www.npmjs.com/package/asciidoctor-jira]
endif::[]

ifdef::awestruct,env-browser[]
toc::[]
endif::[]

A set of macros for https://github.com/asciidoctor/asciidoctor.js[Asciidoctor.js] to integrate Jira!

== Install

=== Node.js

Install the dependencies:

[source, shell]
----
npm i asciidoctor asciidoctor-kroki
----

Create a file named jira.js with following content and run it:

[source, javascript]
----
const asciidoctor = require('@asciidoctor/core')()
const jira = require('asciidoctor-jira')

const input = 'jira::DOC[]'

jira.register(asciidoctor.Extensions) // <1>
console.log(asciidoctor.convert(input, { safe: 'safe' }))

const registry = asciidoctor.Extensions.create()
jira.register(registry) // <2>
console.log(asciidoctor.convert(input, { safe: 'safe', extension_registry: registry }))
----
<1> Register the extension in the global registry
<2> Register the extension in a dedicated registry

=== Antora Integration

If you are using https://antora.org/[Antora], you can integrate Jira in your documentation site.

Install the extension in your playbook project:

[source, shell]
----
npm i asciidoctor-jira
----

Register the extension in your playbook file:

[source, yaml]
----
asciidoc:
  extensions:
    - asciidoctor-jira
----

== Usage

=== block macro

=== inline macro

== Configuration


[cols='1e,2a,3,2a', ]
|===
|Macro type|Attribute name |Description |Default value

|block
|`jql`
|Define the query to obtain issues from jira instance.
|`resolution='Unresolved' ORDER BY priority DESC, key ASC, duedate ASC`


|===

