// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.2.1 (230906a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/asciidoctor/asciidoctor-jira/lfet/roadmap/config.lfet"
// 25.09.2023 16:43
//
// Changes to this code resulting from refactorings can be synchronised
// with LF-ET using the function "Scrapbook Import".
//
// Prolog Decision Table ---->
function config (name, parent, target, attrs, logger) {
  let _step = 1
  let _exit = false
  const config = {
    toJSON: function () {
      const result = {}
      for (const x in this) {
        if (x !== 'jiraUsername' && x !== 'jiraPassword') {
          result[x] = this[x]
        } else {
          if (x === 'jiraUsername' || x === 'jiraPassword') {
            result[x] = this[x].replace(/./g, '*')
          }
        }
      }
      return result
    },
    jiraFields: {
      epicName: 'customfield_10004',
      summary: 'summary',
      status: 'status',
      issueType: 'issuetype',
      resolutionDate: 'resolutiondate',
      dueDate: 'duedate',
      created: 'created'
    },
    getCategoryLabel: function (_catIndex) {
      return this[`${this.categories[_catIndex]}Label`]
    },
    getCategoryJQL: function (_catIndex) {
      return this[`${this.categories[_catIndex]}JQL`]
    }
  }
  let catIndex = -1
  const doc = parent.getDocument()
  do {
    _exit = true
    // $$BasicIndentLevel=2
    // Prolog Decision Table <----
    // Condition C01/01: Step / 1 / jira project key information
    if (_step === 1) {
      // Condition C02: jira project key information is set
      if (target !== undefined) {
        // Rule R01 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 1 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A02: set jira project
        config.projectKey = parent.applySubstitutions(target, ['attributes'])
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R01 <----
      } else {
        // Rule R02 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 2 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A14/01: log mandatory information is missing / JIRA PROJECT / Jira project key is missing
        logger.error('Jira project key is missing')
        // Action A15/03: next step / E / Exit
        _exit = true
        // Rule R02 <----
      }
    // Condition C01/02: Step / 2 / jira base url information
    } else if (_step === 2) {
      // Condition C03/01: jira base url is set / ATTR / via macro attributes
      if (attrs.jiraBaseUrl) {
        // Rule R03 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 3 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A01/01: set jira base url / ATTR / via macro attributes
        config.jiraBaseUrl = attrs.jiraBaseUrl
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R03 <----
      // Condition C03/02: jira base url is set / JIRA_PRJ / via doc attribute and jira project key suffix
      } else if (doc.getAttribute(`${config.projectKey.toLowerCase()}-${name.toLowerCase()}-jira-baseurl`)) {
        // Rule R04 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 4 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A01/03: set jira base url / JIRA_PRJ / via doc attribute and jira project key suffix
        config.jiraBaseUrl = doc.getAttribute(`${config.projectKey.toLowerCase()}.${name}-jira-baseurl`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R04 <----
      // Condition C03/03: jira base url is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-jira-baseurl`)) {
        // Rule R05 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 5 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A01/02: set jira base url / DOC / via doc attribute
        config.jiraBaseUrl = doc.getAttribute(`${name}-jira-baseurl`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R05 <----
      } else {
        // Rule R06 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 6 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A14/02: log mandatory information is missing / BASE_URL / Jira base url is missing
        logger.error('Jira base url is missing')
        // Action A15/03: next step / E / Exit
        _exit = true
        // Rule R06 <----
      }
    // Condition C01/03: Step / 3 / jira username information
    } else if (_step === 3) {
      // Condition C04/01: jira username is set / DOC_PRJ / via doc attribute and jira project key praefix
      if (doc.getAttribute(`${config.projectKey.toLowerCase()}-${name.toLowerCase()}-jira-username`)) {
        // Rule R07 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 7 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A03/02: set jira username / DOC_PRJ / via doc attribute and jira project key praefix
        config.jiraUsername = doc.getAttribute(`${config.projectKey.toLowerCase()}-${name}-jira-username`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R07 <----
      // Condition C04/02: jira username is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-jira-username`)) {
        // Rule R08 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 8 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A03/01: set jira username / DOC / via doc attribute
        config.jiraUsername = doc.getAttribute(`${name}-jira-username`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R08 <----
      // Condition C04/03: jira username is set / ENV_PRJ / via env and jira project key praefix
      } else if (process.env[`${config.projectKey.toUpperCase()}_${name.toUpperCase()}_JIRA_USERNAME`]) {
        // Rule R09 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 9 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A03/04: set jira username / ENV_PRJ / via env and jira project key praefix
        config.jiraUsername = process.env[`${config.projectKey.toUpperCase()}_${name.toUpperCase()}_JIRA_USERNAME`]
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R09 <----
      // Condition C04/04: jira username is set / ENV / via env
      } else if (process.env[`${name.toUpperCase()}_JIRA_USERNAME`]) {
        // Rule R10 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 10 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A03/03: set jira username / ENV / via env
        config.jiraUsername = process.env[`${name.toUpperCase()}_JIRA_USERNAME`]
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R10 <----
      } else {
        // Rule R11 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 11 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A14/03: log mandatory information is missing / JIRA_USR / Jira username is missing
        logger.error('Jira username is missing')
        // Action A15/03: next step / E / Exit
        _exit = true
        // Rule R11 <----
      }
    // Condition C01/04: Step / 4 / jira password / apitoken information
    } else if (_step === 4) {
      // Condition C05/01: jira password / apitoken is set / DOC_PRJ / via doc attribute and jira project key praefix
      if (doc.getAttribute(`${config.projectKey.toLowerCase()}-${name.toLowerCase()}-jira-password`)) {
        // Rule R12 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 12 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A04/02: set jira password / apitoken / DOC_PRJ / via doc attribute and jira project key praefix
        config.jiraPassword = doc.getAttribute(`${config.projectKey.toLowerCase()}-${name}-jira-password`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R12 <----
      // Condition C05/02: jira password / apitoken is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-jira-password`)) {
        // Rule R13 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 13 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A04/01: set jira password / apitoken / DOC / via doc attribute
        config.jiraPassword = doc.getAttribute(`${name}-jira-password`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R13 <----
      // Condition C05/03: jira password / apitoken is set / ENV_PRJ / via env and jira project key praefix
      } else if (process.env[`${config.projectKey.toUpperCase()}_${name.toUpperCase()}_JIRA_PASSWORD`]) {
        // Rule R14 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 14 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A04/04: set jira password / apitoken / ENV_PRJ / via env and jira project key praefix
        config.jiraPassword = process.env[`${config.projectKey.toUpperCase()}_${name.toUpperCase()}_JIRA_PASSWORD`]
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R14 <----
      // Condition C05/04: jira password / apitoken is set / ENV / via env
      } else if (process.env[`${name.toUpperCase()}_JIRA_PASSWORD`]) {
        // Rule R15 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 15 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A04/03: set jira password / apitoken / ENV / via env
        config.jiraPassword = process.env[`${name.toUpperCase()}_JIRA_PASSWORD`]
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R15 <----
      } else {
        // Rule R16 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 16 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A14/04: log mandatory information is missing / JIRA_PWD / Jira password / apitoken is missing
        logger.error('Jira password / apitoken is missing')
        // Action A15/03: next step / E / Exit
        _exit = true
        // Rule R16 <----
      }
    // Condition C01/05: Step / 5 / year information
    } else if (_step === 5) {
      // Condition C06/01: year information is set / ATTR / via macro attributes
      if (attrs.year) {
        // Rule R17 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 17 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A05/01: set year / ATTR / via macro attributes
        config.year = attrs.year
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R17 <----
      // Condition C06/02: year information is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-year`)) {
        // Rule R18 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 18 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A05/02: set year / DOC / via doc attribute
        config.year = doc.getAttribute(`${name}-year`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R18 <----
      } else {
        // Rule R19 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 19 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A05/03: set year / DEF / current year
        config.year = new Date().toLocaleDateString('en-US', { year: 'numeric' })
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R19 <----
      }
    // Condition C01/06: Step / 6 / category information
    } else if (_step === 6) {
      // Condition C07/01: category information is set / ATTR / category information via macro attribute
      if (attrs.categories) {
        // Rule R20 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 20 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A06/01: set categories / ATTR / via macro attributes
        config.categories = attrs.categories.split(',').map(it => it.trim())
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R20 <----
      // Condition C07/02: category information is set / DOC / category information via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-categories`)) {
        // Rule R21 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 21 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A06/02: set categories / DOC / via doc attribute
        config.categories = doc.getAttribute(`${name}-categories`).split(',').map(it => it.trim())
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R21 <----
      } else {
        // Rule R22 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 22 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A06/03: set categories / DEF / maintenance,feature,security,infrastructure,deprecated,migration
        config.categories = 'maintenance,feature,security,infrastructure,deprecated,migration'.split(',').map(it => it.trim())
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R22 <----
      }
    // Condition C01/07: Step / 7 / plantuml-server base url information
    } else if (_step === 7) {
      // Condition C08: plantuml server url is set
      if (doc.getAttribute(`${name.toLowerCase()}-plantuml-server-url`)) {
        // Rule R23 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 23 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A07/01: set plantuml-server base url / SET / set value from doc attribute
        config.plantumlServerUrl = doc.getAttribute(`${name.toLowerCase()}-plantuml-server-url`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R23 <----
      } else {
        // Rule R24 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 24 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A07/02: set plantuml-server base url / DEF / https://kroki.io/plantuml
        config.plantumlServerUrl = 'https://kroki.io/plantuml'
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R24 <----
      }
    // Condition C01/08: Step / 8 / which status should act for closed issues
    } else if (_step === 8) {
      // Condition C09/01: which status should act for closed issues / ATTR / via block macro attributes
      if (attrs['closed-status']) {
        // Rule R25 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 25 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A08/01: set closed status / ATTR / via block macro attribute
        config.closedStatus = attrs[`${name.toLowerCase()}-closed-status`].split(',').map(it => it.trim())
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R25 <----
      // Condition C09/02: which status should act for closed issues / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-closed-status`)) {
        // Rule R26 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 26 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A08/02: set closed status / DOC / via doc attribute
        config.closedStatus = doc.getAttribute(`${name.toLowerCase()}-closed-status`).split(',').map(it => it.trim())
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R26 <----
      } else {
        // Rule R27 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 27 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A08/03: set closed status / DEF / Closed,Resolved
        config.closedStatus = 'Closed,Resolved'.split(',')
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R27 <----
      }
    // Condition C01/09: Step / 9 / plantuml theme option
    } else if (_step === 9) {
      // Condition C10/01: plantuml theme option is set / ATTR / via block macro attr
      if (attrs.theme) {
        // Rule R28 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 28 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A09/02: set plantuml theme option / ATTR / via block macro attribute
        config.plantumlTheme = attrs.theme
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R28 <----
      // Condition C10/02: plantuml theme option is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-theme`)) {
        // Rule R29 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 29 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A09/03: set plantuml theme option / DOC / via doc attribute
        config.plantumlTheme = doc.getAttribute(`${name.toLowerCase()}-theme`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R29 <----
      } else {
        // Rule R30 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 30 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A09/01: set plantuml theme option / DEF / hacker
        config.plantumlTheme = 'hacker'
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R30 <----
      }
    // Condition C01/10: Step / 10 / lastRoadmapReleaseDate
    } else if (_step === 10) {
      // Condition C11/01: last roadmap release date is set / ATTR / via blockmacro attr
      if (attrs['release-date']) {
        // Rule R31 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 31 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A10/01: set last roadmap release date / ATTR / via blockmacro attribute
        config.lastRoadmapReleaseDate = attrs['release-date']
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R31 <----
      // Condition C11/02: last roadmap release date is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-release-date`)) {
        // Rule R32 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 32 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A10/02: set last roadmap release date / DOC / via doc attribute
        config.lastRoadmapReleaseDate = doc.getAttribute(`${name.toLowerCase()}-release-date`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R32 <----
      } else {
        // Rule R33 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 33 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A10/03: set last roadmap release date / UDEF / not set
        config.lastRoadmapReleaseDate = undefined
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R33 <----
      }
    // Condition C01/11: Step / 11 / legend for status
    } else if (_step === 11) {
      // Condition C12/01: legend for status is set / ATTR / via block macro attribute
      if (attrs['legend-for-status']) {
        // Rule R34 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 34 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A11/02: set legend for status / ATTR / via block macro attribute
        config.legendForStatus = attrs['legend-for-status'].split(',').map(it => it.trim())
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R34 <----
      // Condition C12/02: legend for status is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-legend-for-status`)) {
        // Rule R35 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 35 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A11/03: set legend for status / DOC / via doc attribute
        config.legendForStatus = doc.getAttribute(`${name.toLowerCase()}-legend-for-status`).split(',').map(it => it.trim())
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R35 <----
      } else {
        // Rule R36 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 36 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A11/01: set legend for status / DEF / Open,In Progress,Closed
        config.legendForStatus = 'Open,In Progress,Closed'.split(',').map(it => it.trim())
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R36 <----
      }
    // Condition C01/12: Step / 12 / check for more categories to process
    } else if (_step === 12) {
      // Prolog Condition C13 ---->
      catIndex++
      // Prolog Condition C13 <----
      // Condition C13: one more category to process
      if (catIndex < config.categories.length) {
        // Rule R37 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 37 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R37 <----
      } else {
        // Rule R38 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 38 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A15/03: next step / E / Exit
        _exit = true
        // Rule R38 <----
      }
    // Condition C01/13: Step / 12a / label for category
    } else if (_step === 13) {
      // Condition C14/01: label for category is set / ATTR / via block macro attribute
      if (attrs[`${config.categories[catIndex]}-label`]) {
        // Rule R39 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 39 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A12/01: set category label / ATTR / via block macro attribute
        config[`${config.categories[catIndex]}Label`] = attrs[`${config.categories[catIndex]}-label`]
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R39 <----
      // Condition C14/02: label for category is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-${config.categories[catIndex]}-label`)) {
        // Rule R40 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 40 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A12/02: set category label / DOC / via doc attribute
        config[`${config.categories[catIndex]}Label`] = doc.getAttribute(`${name.toLowerCase()}-${config.categories[catIndex]}-label`)
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R40 <----
      } else {
        // Rule R41 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 41 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A12/03: set category label / DEF / set category as default label
        config[`${config.categories[catIndex]}Label`] = config.categories[catIndex]
        // Action A15/01: next step / + / next step
        _step++
        _exit = false
        // Rule R41 <----
      }
    } else {
      // Condition C15/01: jql for category is set / ATTR / via block macro attribute
      if (attrs[`${config.categories[catIndex]}-jql`]) {
        // Rule R42 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 42 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A13/01: set category jql / ATTR / via block macro attribute
        const categoryJQLSuffixPart = attrs[`${config.categories[catIndex]}-jql`]
        config[`${config.categories[catIndex]}JQL`] = `project = ${config.projectKey} and labels in (Roadmap) and labels in ('${config.year}') and labels in (${config.categories[catIndex]}) and ${categoryJQLSuffixPart}`
        // Action A15/02: next step / 12 / check for more categories to process
        _step = 12
        _exit = false
        // Rule R42 <----
      // Condition C15/02: jql for category is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-${config.categories[catIndex]}-jql`)) {
        // Rule R43 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 43 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A13/02: set category jql / DOC / via doc attribute
        const categoryJQLSuffixPart = doc.getAttribute(`${name.toLowerCase()}-${config.categories[catIndex]}-jql`)
        config[`${config.categories[catIndex]}JQL`] = `project = ${config.projectKey} and labels in (Roadmap) and labels in ('${config.year}') and labels in (${config.categories[catIndex]}) and ${categoryJQLSuffixPart}`
        // Action A15/02: next step / 12 / check for more categories to process
        _step = 12
        _exit = false
        // Rule R43 <----
      } else {
        // Rule R44 ---->
        // Trace ---->
        logger.info(`config - 20230925.164323 - 44 / 44 - ${JSON.stringify(config)}`)
        // Trace <----
        // Action A13/03: set category jql / DEF / set category as default label
        config[`${config.categories[catIndex]}JQL`] = `project = ${config.projectKey} and labels in (Roadmap) and labels in ('${config.year}') and labels in (${config.categories[catIndex]})`
        // Action A15/02: next step / 12 / check for more categories to process
        _step = 12
        _exit = false
        // Rule R44 <----
      }
    }
    // Epilog Decision Table ---->
  } while (_exit === false)
  return config
}

module.exports = {
  createConfig: (name, parent, target, attrs, logger) => {
    return config(name, parent, target, attrs, logger)
  }
}
// Epilog Decision Table <----

// End of generated JavaScript source code
// Generated by LF-ET 2.2.1 (230906a), https://www.lohrfink.de/lfet
