// *** WARNING: DO NOT MODIFY *** This is a generated JavaScript source code!
//
// Generated by LF-ET 2.2.1 (230906a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/asciidoctor/asciidoctor-jira/lfet/blockmacro/roadmapBlockmacroConfig.lfet"
// 27.09.2023 22:03
//
// Changes to this code resulting from refactorings can be synchronised
// with LF-ET using the function "Scrapbook Import".
//
// Prolog Decision Table ---->
function roadmapBlockmacroConfig (name, parent, target, attrs, logger) {
  let _step = 1
  let _exit = false
  const _roadmapBlockmacroConfig = {
    toJSON: function () {
      const result = {}
      for (const x in this) {
        if (x !== 'jiraUsername' && x !== 'jiraPassword') {
          result[x] = this[x]
        } else {
          if (x === 'jiraUsername' || x === 'jiraPassword') {
            result[x] = this[x].replace(/./g, '*')
          }
        }
      }
      return result
    },
    jiraFields: {
      epicName: 'customfield_10004',
      summary: 'summary',
      status: 'status',
      issueType: 'issuetype',
      resolutionDate: 'resolutiondate',
      dueDate: 'duedate',
      created: 'created'
    },
    getCategoryLabel: function (_catIndex) {
      return this[`${this.categories[_catIndex]}Label`]
    },
    getCategoryJQL: function (_catIndex) {
      return this[`${this.categories[_catIndex]}JQL`]
    }
  }
  let catIndex = -1
  const doc = parent.getDocument()
  do {
    _exit = true
    // $$BasicIndentLevel=2
    // Prolog Decision Table <----
    // Condition C01/01: Step / 1 / jira project key information
    if (_step === 1) {
      // Condition C02: jira project key information is set
      if (target !== undefined) {
        // Rule R01 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 1 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A01: set jira project
        _roadmapBlockmacroConfig.projectKey = parent.applySubstitutions(target, ['attributes'])
        // Action A02: load jira config
        _roadmapBlockmacroConfig.jira = require('../common/jiraConfig').createConfig(name, parent, _roadmapBlockmacroConfig.projectKey, attrs, logger)
        // Action A03: load plantuml config
        _roadmapBlockmacroConfig.plantuml = require('../common/plantumlConfig').createConfig(name, parent, attrs, logger)
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R01 <----
      } else {
        // Rule R02 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 2 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A11/01: log mandatory information is missing / PRJ / Jira project key is missing
        logger.error('Jira project key is missing')
        // Action A12/03: next step / E / Exit
        _exit = true
        // Rule R02 <----
      }
    // Condition C01/02: Step / 2 / year information
    } else if (_step === 2) {
      // Condition C03/01: year information is set / ATTR / via macro attributes
      if (attrs.year) {
        // Rule R03 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 3 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A04/01: set year / ATTR / via macro attributes
        _roadmapBlockmacroConfig.year = attrs.year
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R03 <----
      // Condition C03/02: year information is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-year`)) {
        // Rule R04 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 4 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A04/02: set year / DOC / via doc attribute
        _roadmapBlockmacroConfig.year = doc.getAttribute(`${name}-year`)
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R04 <----
      } else {
        // Rule R05 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 5 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A04/03: set year / DEF / current year
        _roadmapBlockmacroConfig.year = new Date().toLocaleDateString('en-US', { year: 'numeric' })
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R05 <----
      }
    // Condition C01/03: Step / 3 / category information
    } else if (_step === 3) {
      // Condition C04/01: category information is set / ATTR / category information via macro attribute
      if (attrs.categories) {
        // Rule R06 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 6 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A05/01: set categories / ATTR / via macro attributes
        _roadmapBlockmacroConfig.categories = attrs.categories.split(',').map(it => it.trim())
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R06 <----
      // Condition C04/02: category information is set / DOC / category information via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-categories`)) {
        // Rule R07 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 7 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A05/02: set categories / DOC / via doc attribute
        _roadmapBlockmacroConfig.categories = doc.getAttribute(`${name}-categories`).split(',').map(it => it.trim())
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R07 <----
      } else {
        // Rule R08 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 8 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A05/03: set categories / DEF / maintenance,feature,security,infrastructure,deprecated,migration
        _roadmapBlockmacroConfig.categories = 'maintenance,feature,security,infrastructure,deprecated,migration'.split(',').map(it => it.trim())
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R08 <----
      }
    // Condition C01/04: Step / 4 / which status should act for closed issues
    } else if (_step === 4) {
      // Condition C05/01: which status should act for closed issues / ATTR / via block macro attributes
      if (attrs['closed-status']) {
        // Rule R09 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 9 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A06/01: set closed status / ATTR / via block macro attribute
        _roadmapBlockmacroConfig.closedStatus = attrs[`${name.toLowerCase()}-closed-status`].split(',').map(it => it.trim())
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R09 <----
      // Condition C05/02: which status should act for closed issues / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-closed-status`)) {
        // Rule R10 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 10 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A06/02: set closed status / DOC / via doc attribute
        _roadmapBlockmacroConfig.closedStatus = doc.getAttribute(`${name.toLowerCase()}-closed-status`).split(',').map(it => it.trim())
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R10 <----
      } else {
        // Rule R11 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 11 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A06/03: set closed status / DEF / Closed,Resolved
        _roadmapBlockmacroConfig.closedStatus = 'Closed,Resolved'.split(',')
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R11 <----
      }
    // Condition C01/05: Step / 5 / lastRoadmapReleaseDate
    } else if (_step === 5) {
      // Condition C06/01: last roadmap release date is set / ATTR / via blockmacro attr
      if (attrs['release-date']) {
        // Rule R12 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 12 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A07/01: set last roadmap release date / ATTR / via blockmacro attribute
        _roadmapBlockmacroConfig.lastRoadmapReleaseDate = attrs['release-date']
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R12 <----
      // Condition C06/02: last roadmap release date is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-release-date`)) {
        // Rule R13 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 13 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A07/02: set last roadmap release date / DOC / via doc attribute
        _roadmapBlockmacroConfig.lastRoadmapReleaseDate = doc.getAttribute(`${name.toLowerCase()}-release-date`)
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R13 <----
      } else {
        // Rule R14 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 14 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A07/03: set last roadmap release date / UDEF / not set
        _roadmapBlockmacroConfig.lastRoadmapReleaseDate = undefined
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R14 <----
      }
    // Condition C01/06: Step / 6 / legend for status
    } else if (_step === 6) {
      // Condition C07/01: legend for status is set / ATTR / via block macro attribute
      if (attrs['legend-for-status']) {
        // Rule R15 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 15 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A08/02: set legend for status / ATTR / via block macro attribute
        _roadmapBlockmacroConfig.legendForStatus = attrs['legend-for-status'].split(',').map(it => it.trim())
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R15 <----
      // Condition C07/02: legend for status is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-legend-for-status`)) {
        // Rule R16 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 16 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A08/03: set legend for status / DOC / via doc attribute
        _roadmapBlockmacroConfig.legendForStatus = doc.getAttribute(`${name.toLowerCase()}-legend-for-status`).split(',').map(it => it.trim())
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R16 <----
      } else {
        // Rule R17 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 17 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A08/01: set legend for status / DEF / Open,In Progress,Closed
        _roadmapBlockmacroConfig.legendForStatus = 'Open,In Progress,Closed'.split(',').map(it => it.trim())
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R17 <----
      }
    // Condition C01/07: Step / 7 / check for more categories to process
    } else if (_step === 7) {
      // Prolog Condition C08 ---->
      catIndex++
      // Prolog Condition C08 <----
      // Condition C08: one more category to process
      if (catIndex < _roadmapBlockmacroConfig.categories.length) {
        // Rule R18 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 18 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R18 <----
      } else {
        // Rule R19 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 19 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A12/03: next step / E / Exit
        _exit = true
        // Rule R19 <----
      }
    // Condition C01/08: Step / 8a / label for category
    } else if (_step === 8) {
      // Condition C09/01: label for category is set / ATTR / via block macro attribute
      if (attrs[`${_roadmapBlockmacroConfig.categories[catIndex]}-label`]) {
        // Rule R20 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 20 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A09/01: set category label / ATTR / via block macro attribute
        _roadmapBlockmacroConfig[`${_roadmapBlockmacroConfig.categories[catIndex]}Label`] = attrs[`${_roadmapBlockmacroConfig.categories[catIndex]}-label`]
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R20 <----
      // Condition C09/02: label for category is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-${_roadmapBlockmacroConfig.categories[catIndex]}-label`)) {
        // Rule R21 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 21 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A09/02: set category label / DOC / via doc attribute
        _roadmapBlockmacroConfig[`${_roadmapBlockmacroConfig.categories[catIndex]}Label`] = doc.getAttribute(`${name.toLowerCase()}-${_roadmapBlockmacroConfig.categories[catIndex]}-label`)
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R21 <----
      } else {
        // Rule R22 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 22 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A09/03: set category label / DEF / set category as default label
        _roadmapBlockmacroConfig[`${_roadmapBlockmacroConfig.categories[catIndex]}Label`] = _roadmapBlockmacroConfig.categories[catIndex]
        // Action A12/01: next step / + / next step
        _step++
        _exit = false
        // Rule R22 <----
      }
    } else {
      // Condition C10/01: jql for category is set / ATTR / via block macro attribute
      if (attrs[`${_roadmapBlockmacroConfig.categories[catIndex]}-jql`]) {
        // Rule R23 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 23 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A10/01: set category jql / ATTR / via block macro attribute
        const categoryJQLSuffixPart = attrs[`${_roadmapBlockmacroConfig.categories[catIndex]}-jql`]
        _roadmapBlockmacroConfig[`${_roadmapBlockmacroConfig.categories[catIndex]}JQL`] = `project = ${_roadmapBlockmacroConfig.projectKey} and labels in (Roadmap) and labels in ('${_roadmapBlockmacroConfig.year}') and ${categoryJQLSuffixPart}`
        // Action A12/02: next step / 7 / check for more categories to process
        _step = 7
        _exit = false
        // Rule R23 <----
      // Condition C10/02: jql for category is set / DOC / via doc attribute
      } else if (doc.getAttribute(`${name.toLowerCase()}-${_roadmapBlockmacroConfig.categories[catIndex]}-jql`)) {
        // Rule R24 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 24 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A10/02: set category jql / DOC / via doc attribute
        const categoryJQLSuffixPart = doc.getAttribute(`${name.toLowerCase()}-${_roadmapBlockmacroConfig.categories[catIndex]}-jql`)
        _roadmapBlockmacroConfig[`${_roadmapBlockmacroConfig.categories[catIndex]}JQL`] = `project = ${_roadmapBlockmacroConfig.projectKey} and labels in (Roadmap) and labels in ('${_roadmapBlockmacroConfig.year}') and ${categoryJQLSuffixPart}`
        // Action A12/02: next step / 7 / check for more categories to process
        _step = 7
        _exit = false
        // Rule R24 <----
      } else {
        // Rule R25 ---->
        // Trace ---->
        logger.info(`roadmapBlockmacroConfig - 20230927.220321 - 25 / 25 - ${JSON.stringify(_roadmapBlockmacroConfig)}`)
        // Trace <----
        // Action A10/03: set category jql / DEF / set category as default label
        _roadmapBlockmacroConfig[`${_roadmapBlockmacroConfig.categories[catIndex]}JQL`] = `project = ${_roadmapBlockmacroConfig.projectKey} and labels in (Roadmap) and labels in ('${_roadmapBlockmacroConfig.year}') and labels in (${_roadmapBlockmacroConfig.categories[catIndex]})`
        // Action A12/02: next step / 7 / check for more categories to process
        _step = 7
        _exit = false
        // Rule R25 <----
      }
    }
    // Epilog Decision Table ---->
  } while (_exit === false)
  return _roadmapBlockmacroConfig
}

module.exports = {
  createConfig: (name, parent, target, attrs, logger) => {
    return roadmapBlockmacroConfig(name, parent, target, attrs, logger)
  }
}
// Epilog Decision Table <----

// End of generated JavaScript source code
// Generated by LF-ET 2.2.1 (230906a), https://www.lohrfink.de/lfet
