name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 12.x
          - 14.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: create .env
        if: runner.os == 'Linux'
        run: |
          cat << EOF > .env
          AJE_USERNAME=${{ secrets.AJE_USERNAME }}
          AJE_APITOKEN=${{ secrets.AJE_APITOKEN }}
          AJE_JIRABASEURL=${{ secrets.AJE_JIRABASEURL }}
          EOF

      - name: create .env
        if: runner.os == 'Windows'
        run: |
          "AJE_USERNAME=${{ secrets.AJE_USERNAME }}" | ac .env
          "AJE_APITOKEN=${{ secrets.AJE_APITOKEN }}"  | ac .env
          "AJE_JIRABASEURL=${{ secrets.AJE_JIRABASEURL }}"  | ac .env

      - name: test
        run: npm test

      - name: Upload generated documentation for deploy step
        uses: actions/upload-artifact@v2
        if: runner.os == 'Linux' && matrix.node-version == '14.x'
        with:
          name: documentation
          path: test/antora/public

  deploy-documentation:
    runs-on: ubuntu-latest
    needs: build
    steps:

      - uses: actions/download-artifact@v2
        with:
          name: documentation

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
