name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 22.x
          - 24.x
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up NodeJs ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: create .env
        if: runner.os == 'Linux'
        run: |
          cat << EOF > .env
          JIRA_CLOUD_NAME=${{ secrets.JIRA_CLOUD_NAME }}
          JIRA_CLIENT_ID=${{ secrets.JIRA_CLIENT_ID }}
          JIRA_CLIENT_SECRET=${{ secrets.JIRA_CLIENT_SECRET }}
          EOF

      - name: create .env
        if: runner.os == 'Windows'
        run: |
          "JIRA_CLOUD_NAME=${{ secrets.JIRA_CLOUD_NAME }}" | ac .env
          "JIRA_CLIENT_ID=${{ secrets.JIRA_CLIENT_ID }}"  | ac .env
          "JIRA_CLIENT_SECRET=${{ secrets.JIRA_CLIENT_SECRET }}"  | ac .env

      - name: test
        run: npm test
